---@class WeaponComponent
---@field Update fun(self: WeaponComponent, context: Context, interpolationUpdate: boolean)
---@field GetFocusEntity fun(self: WeaponComponent): EntityComponent?
---@field GetMaxCharge fun(self: WeaponComponent): number
---@field m_weaponType WeaponType | integer
---@field m_fireDelay number
---@field m_maxFireDelay number
---@field m_weaponModifiers WeaponModifier | integer
---@field m_charge number
---@field m_directionBuffer Vector -- used as a buffer to store a previous direction (usually for effects that require the direction to not change even on dropped inputs), individually managed by each weapon (mostly by Fire and Reset)
---@field m_targetPosition Vector
---@field m_owner EntityComponent?