---@class Component.EntityConfig
---@field m_map table<integer, Component.EntityConfig.Entity> : 0x0
---@field m_players Component.EntityConfig.Player[] : 0x8
---@field m_babies Component.EntityConfig.Baby[] : 0x14
---@field m_bosses Component.EntityConfig.Boss[] : 0x20
---@field m_edenHair string[] : 0x2c
---@field m_pokeyMansPool Component.EntityConfig.PokeyMansEntry : 0x38

---@class Component.EntityConfig.PokeyMansEntry
---@field type EntityType | integer : 0x0
---@field variant integer : 0x4
---@field subType integer : 0x8
---@field baseHp integer : 0xc
---@field maybeStageHp integer : 0x10