---@class PlayerContext.TakeDamage : IsaacContext.PlaySound, InventoryContext.HasCollectible, BishopProtectionContext.FindClosestBishop, BishopProtectionContext.TriggerProtectPlayer, InvincibilityContext.HasInvincibility, AstralProjectionContext.TryEndAstralProjection
---@field sfxManager SfxManagerComponent
---@field level Component.Level
---@field room Component.Room
---@field persistentGameData Component.PersistentGameData
---@field itemConfig Component.ItemConfig.Item
---@field proceduralItemManager ProceduralItemManagerComponent
---@field seeds SeedsComponent
---@field frameCount integer
---@field challenge Challenge | integer
---@field dailyChallenge DailyChallengeComponent
---@field defaultPlayer Component.Entity.Player?
---@field forceUnlock boolean