---@class RoomComponent
---@field m_type RoomType | integer
---@field m_roomDescriptor RoomDescriptorComponent
---@field m_entityList EntityListComponent
---@field m_bossCount integer
---@field m_waterAmount number
---@field m_renderScrollOffset Vector