---@class BackwardsStageDescComponent
---@field bossRoomDesc Component.RoomDescriptor[]
---@field treasureRoomDesc Component.RoomDescriptor[]
---@field numBossRooms integer
---@field numTreasureRooms integer
---@field stageType StageType
---@field isXL boolean