---@class EntityComponent
---@field Free fun(self: EntityComponent, context: Context)
---@field Init fun(self: EntityComponent, context: Context, type: EntityType | integer, variant: integer, subtype: integer, seed: integer)
---@field Update fun(self: EntityComponent, context: Context)
---@field Remove fun(self: EntityComponent, context: Context)
---@field TakeDamage fun(self: EntityComponent, context: Context, damage: number, flags: DamageFlag | integer, source: EntityRefComponent, damageCountdown: integer)
---@field SetCollisionDamage fun(self: EntityComponent, context: Context, collisionDamage: number)
---@field CanShutDoors fun(self: EntityComponent) : boolean
---@field IsBoss fun(self: EntityComponent) : boolean
---@field m_type EntityType | integer
---@field m_variant integer
---@field m_subtype integer
---@field m_config EntityConfig.EntityComponent
---@field m_initSeed integer
---@field m_dropRNG RNG
---@field m_position Vector
---@field m_velocity Vector
---@field m_size number
---@field m_sizeMulti Vector
---@field m_shadowSize number
---@field m_initialFriction number
---@field m_friction number
---@field m_timescale number
---@field m_localFrame number -- local "Time" for the entity, affected by timeScale
---@field m_lastLocalFrame number
---@field m_spawnFrame integer
---@field m_flags EntityFlag | integer
---@field m_entityCollisionClass EntityCollisionClass | integer
---@field m_gridCollisionClass EntityGridCollisionClass | integer
---@field m_collisionDamage number
---@field m_maxHealth number
---@field m_health number
---@field m_velocityOnGridCollide Vector
---@field m_gridCollisionDirection Vector
---@field m_gridCollisionPoints Vector[]
---@field m_backPointers Set<EntityPtrComponent>
---@field m_parent EntityPtrComponent
---@field m_child EntityPtrComponent
---@field m_targetPosition Vector
---@field m_positionOffset Vector
---@field m_depthOffset number
---@field m_spawnerEntity EntityPtrComponent
---@field m_spawnerType EntityType | integer
---@field m_target EntityPtrComponent
---@field m_minecart EntityPtrComponent
---@field m_sprite Sprite
---@field m_preInterpolatePosition Vector
---@field m_exists boolean
---@field m_isDead boolean
---@field m_visible boolean
---@field m_invincible boolean
---@field m_valid boolean
---@field m_interpolated boolean
---@field m_collidesWithGrid boolean

---@class EntityPtrComponent
---@field ref EntityComponent?