---@class FamiliarContext.GetOrbitTarget : InventoryContext.HasCollectible
---@field level Component.Level
---@field room Component.Room
---@field persistentGameData PersistentDataComponent
---@field itemConfig Component.ItemConfig.Item
---@field proceduralItemManager ProceduralItemManagerComponent
---@field seeds SeedsComponent
---@field frameCount integer
---@field challenge Challenge | integer
---@field dailyChallenge DailyChallengeComponent
---@field defaultPlayer Component.Entity.Player?
---@field forceUnlock boolean
---@field entityList EntityManagerComponent

---@class FamiliarContext.GetOrbitPosition : EntityContext.GetFrame, InventoryContext.GetTrinketMultiplier
---@field isInterpolation boolean
---@field level Component.Level
---@field room Component.Room
---@field persistentGameData PersistentDataComponent
---@field itemConfig Component.ItemConfig.Item
---@field proceduralItemManager ProceduralItemManagerComponent
---@field seeds SeedsComponent
---@field frameCount integer
---@field challenge Challenge | integer
---@field dailyChallenge DailyChallengeComponent
---@field defaultPlayer Component.Entity.Player?
---@field forceUnlock boolean