---@class Engine.Image
---@field IsLoaded fun(self: Engine.Image): boolean
---@field Render_SourceDestQuad fun(self: Engine.Image, sourceQuad: SourceQuad, destQuad: DestinationQuad, colorTopLeft: KColor, colorTopRight: KColor, colorBottomLeft: KColor, colorBottomRight: KColor): number[]?
---@field Render_SourceDestQuadFlatColor fun(self: Engine.Image, sourceQuad: SourceQuad, destQuad: DestinationQuad, color: KColor): number[]?
---@field Render_DestQuadFlatColor fun(self: Engine.Image, position: DestinationQuad, color: KColor): number[]
---@field Render_PositionFlatColor fun(self: Engine.Image, position: Vector, color: KColor): number[]
---@field GetWidth fun(self: Engine.Image): integer
---@field GetHeight fun(self: Engine.Image): integer
---@field GetPaddedWidth fun(self: Engine.Image): integer
---@field GetPaddedHeight fun(self: Engine.Image): integer
---@field GetBytesPerPixel fun(self: Engine.Image): integer
---@field SetVertexFormat fun(self: Engine.Image, format: Engine.VertexAttributeDescriptor[]) 
---@field SetFilterMode fun(self: Engine.Image, minFilterMode: integer, magFilterMode: integer)
---@field SetWrapMode fun(self: Engine.Image, wrapSMode: integer, wrapTMode: integer)
---@field IsPalleted fun(self: Engine.Image): boolean
---@field SetPallete fun(self: Engine.Image, value: boolean)
---@field SetTexel fun(self: Engine.Image)
---@field GetTexel fun(self: Engine.Image)
---@field GetTexelRegion fun(self: Engine.Image)
---@field RenderTexturedTriangle fun(self: Engine.Image)
---@field Load fun(self: Engine.Image)
---@field SwapBatches fun(self: Engine.Image)
---@field FreeBatches fun(self: Engine.Image)
---@field Unload fun(self: Engine.Image)
---@field Reload fun(self: Engine.Image)
---@field UnloadImageData fun(self: Engine.Image)
---@field Bind fun(self: Engine.Image)
---@field ApplyPallette fun(self: Engine.Image)
---@field apply_image fun(self: Engine.Image)
---@field BeginBatch fun(self: Engine.Image, transparent: boolean)
---@field EndBatch fun(self: Engine.Image)

---@class Engine.ProceduralImage : Engine.Image