---@class Admin
---@field context Context

---@class Context
---@field GetStaticContext fun(self: Context): StaticContext
---@field GetGame fun(self: Context): GameComponent
---@field GetLevel fun(self: Context): LevelComponent
---@field GetRoom fun(self: Context): RoomComponent
---@field GetPlayerManager fun(self: Context): PlayerManagerComponent
---@field GetItemPool fun(self: Context): ItemPoolComponent
---@field GetSeeds fun(self: Context): SeedsComponent
---@field GetOptions fun(self: Context): OptionsComponent
---@field GetInput fun(self: Context): InputComponent
---@field GetScreen fun(self: Context): ScreenComponent
---@field GetStageTransition fun(self: Context): StageTransitionComponent
---@field GetDeathmatchManager fun(self: Context): DeathmatchManagerComponent