---@class TemporaryEffectsComponent
---@field m_cacheFlags CacheFlag | integer : 0x0
---@field m_effects TemporaryEffectComponent[] : 0x4
---@field m_shouldEvaluateCache_qqq boolean : 0x10
---@field m_disabled boolean : 0x11
---@field m_player EntityPlayerComponent : 0x14

---@class TemporaryEffectComponent
---@field m_item ItemConfigItemComponent : 0x0
---@field m_count integer : 0x4
---@field m_cooldown integer : 0x8