---@class MultiShotParamsComponent
---@field numTears integer
---@field numLanesPerEye integer
---@field spreadAngleTears number
---@field spreadAngleLaser number
---@field spreadAngleTechX number
---@field spreadAngleKnives number
---@field numEyesActive integer
---@field multiEyeAngle number
---@field isCrossEyed boolean
---@field isShootingBackwards boolean
---@field isShootingSideways boolean
---@field numRandomTears integer

---@class TearHitParamsComponent
---@field tearVariant TearVariant | integer
---@field bombVariant BombVariant | integer
---@field tearColor Color
---@field tearFlags BitSet128
---@field tearDamage number
---@field tearScale number
---@field tearHeight number
---@field knockback number
---@field height number
---@field speed number
---@field velocityMultiplier number