---@class RoomUpdateContext.Update : RoomContext.GetFrameCount, InventoryContext.HasCollectible, LevelContext.GetStageId, DamoclesItemsContext.Update
---@field game Component.Game
---@field level Component.Level
---@field playerManager PlayerManagerComponent
---@field musicManager MusicManagerComponent
---@field ambush AmbushComponent
---@field frameCount integer
---@field room Component.Room
---@field persistentGameData PersistentDataComponent
---@field itemConfig Component.ItemConfig.Item
---@field proceduralItemManager ProceduralItemManagerComponent
---@field seeds SeedsComponent
---@field challenge Challenge | integer -- Trinket
---@field dailyChallenge DailyChallengeComponent -- Trinket
---@field defaultPlayer Component.Entity.Player? -- Both
---@field forceUnlock boolean
---@field mode integer