---@class RoomUpdateContext.Update : RoomContext.GetFrameCount, InventoryContext.HasCollectible, LevelContext.GetStageId, DamoclesItemsContext.Update
---@field game Component.Game
---@field level Component.Level
---@field playerManager Component.PlayerManager
---@field musicManager MusicManagerComponent
---@field ambush AmbushComponent
---@field frameCount integer
---@field room Component.Room
---@field persistentGameData Component.PersistentGameData
---@field itemConfig Component.ItemConfig.Item
---@field proceduralItemManager Component.ProceduralItemManager
---@field seeds Component.Seeds
---@field challenge Challenge | integer -- Trinket
---@field dailyChallenge Component.DailyChallenge -- Trinket
---@field defaultPlayer Component.Entity.Player? -- Both
---@field forceUnlock boolean
---@field mode integer